-- Create Sample Users Script
-- This script creates sample users for testing the Real Estate Marketplace
-- Note: Passwords will be hashed by the application, so this is just for reference

-- Sample User Data for Testing
-- These users can be created through the registration API endpoint

-- User 1: John Doe
-- Email: john@example.com
-- Password: password123
-- Phone: +1-555-0101

-- User 2: Jane Smith  
-- Email: jane@example.com
-- Password: password123
-- Phone: +1-555-0102

-- User 3: Mike Johnson
-- Email: mike@example.com
-- Password: password123
-- Phone: +1-555-0103

-- User 4: Sarah Wilson
-- Email: sarah@example.com
-- Password: password123
-- Phone: +1-555-0104

-- User 5: David Brown
-- Email: david@example.com
-- Password: password123
-- Phone: +1-555-0105

-- To create these users, use the registration API endpoint:
-- POST /api/auth/register
-- 
-- Example request body:
-- {
--   "name": "John Doe",
--   "email": "john@example.com", 
--   "phone": "+1-555-0101",
--   "password": "password123"
-- }

-- After creating users through the API, you can run the seed-database.sql script
-- to create sample listings associated with these users.

-- Note: Make sure to replace the 'user_id_placeholder' values in the listings
-- with the actual user IDs generated by the application.
